apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: fr3d3rico/udagram-api-feed
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        resources: #This resource is needed to avoid Scaling FailedGetResourceMetric error
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            configMapKeyRef:
              name: env-udagram-config-map
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: env-udagram-config-map
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: env-udagram-config-map
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: env-udagram-config-map
              key: POSTGRES_DB
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-udagram-config-map
              key: AWS_BUCKET
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env-udagram-config-map
              key: AWS_REGION
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: env-udagram-config-map
              key: AWS_PROFILE
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: env-udagram-config-map
              key: JWT_SECRET
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-udagram-config-map
              key: URL
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret